### ISSUE TITLE
two function calls in same line result in nullptr exception

### ISSUE THREAD

**Issue by niansa** [Dominilk/coda-std#1]
![grafik](https://user-images.githubusercontent.com/20720267/106380851-456e0280-63b5-11eb-96fa-3fa98c1b819c.png)

**Comment by Dominilk** [comment]
Separate the two lines with a semicolon. Then it should work. Error message will be changed with coda3, releasing in a few months :). If there are no further questions, I will close this issue.

**Comment by Dominilk** [comment]
BTW, I think you’re running coda from the playground, the performance is very limited as I can not provide that many resources on my vps
